// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentinstance"
	"github.com/looplj/axonhub/internal/ent/agentruntime"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// AgentRuntimeUpdate is the builder for updating AgentRuntime entities.
type AgentRuntimeUpdate struct {
	config
	hooks     []Hook
	mutation  *AgentRuntimeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AgentRuntimeUpdate builder.
func (_u *AgentRuntimeUpdate) Where(ps ...predicate.AgentRuntime) *AgentRuntimeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentRuntimeUpdate) SetUpdatedAt(v time.Time) *AgentRuntimeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentRuntimeUpdate) SetDeletedAt(v int) *AgentRuntimeUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableDeletedAt(v *int) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AgentRuntimeUpdate) AddDeletedAt(v int) *AgentRuntimeUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentRuntimeUpdate) SetName(v string) *AgentRuntimeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableName(v *string) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AgentRuntimeUpdate) SetType(v agentruntime.Type) *AgentRuntimeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableType(v *agentruntime.Type) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentRuntimeUpdate) SetStatus(v agentruntime.Status) *AgentRuntimeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableStatus(v *agentruntime.Status) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *AgentRuntimeUpdate) SetHost(v string) *AgentRuntimeUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableHost(v *string) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetUser sets the "user" field.
func (_u *AgentRuntimeUpdate) SetUser(v string) *AgentRuntimeUpdate {
	_u.mutation.SetUser(v)
	return _u
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableUser(v *string) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetUser(*v)
	}
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *AgentRuntimeUpdate) SetAuthMethod(v agentruntime.AuthMethod) *AgentRuntimeUpdate {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableAuthMethod(v *agentruntime.AuthMethod) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *AgentRuntimeUpdate) SetPassword(v string) *AgentRuntimeUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillablePassword(v *string) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSSHPrivateKey sets the "ssh_private_key" field.
func (_u *AgentRuntimeUpdate) SetSSHPrivateKey(v string) *AgentRuntimeUpdate {
	_u.mutation.SetSSHPrivateKey(v)
	return _u
}

// SetNillableSSHPrivateKey sets the "ssh_private_key" field if the given value is not nil.
func (_u *AgentRuntimeUpdate) SetNillableSSHPrivateKey(v *string) *AgentRuntimeUpdate {
	if v != nil {
		_u.SetSSHPrivateKey(*v)
	}
	return _u
}

// AddInstanceIDs adds the "instances" edge to the AgentInstance entity by IDs.
func (_u *AgentRuntimeUpdate) AddInstanceIDs(ids ...int) *AgentRuntimeUpdate {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the AgentInstance entity.
func (_u *AgentRuntimeUpdate) AddInstances(v ...*AgentInstance) *AgentRuntimeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// Mutation returns the AgentRuntimeMutation object of the builder.
func (_u *AgentRuntimeUpdate) Mutation() *AgentRuntimeMutation {
	return _u.mutation
}

// ClearInstances clears all "instances" edges to the AgentInstance entity.
func (_u *AgentRuntimeUpdate) ClearInstances() *AgentRuntimeUpdate {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to AgentInstance entities by IDs.
func (_u *AgentRuntimeUpdate) RemoveInstanceIDs(ids ...int) *AgentRuntimeUpdate {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to AgentInstance entities.
func (_u *AgentRuntimeUpdate) RemoveInstances(v ...*AgentInstance) *AgentRuntimeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentRuntimeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentRuntimeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentRuntimeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentRuntimeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentRuntimeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentruntime.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentruntime.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentruntime.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentRuntimeUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := agentruntime.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentruntime.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := agentruntime.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.auth_method": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentRuntimeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentRuntimeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentRuntimeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentruntime.Table, agentruntime.Columns, sqlgraph.NewFieldSpec(agentruntime.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentruntime.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentruntime.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(agentruntime.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentruntime.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(agentruntime.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentruntime.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(agentruntime.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.User(); ok {
		_spec.SetField(agentruntime.FieldUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(agentruntime.FieldAuthMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(agentruntime.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.SSHPrivateKey(); ok {
		_spec.SetField(agentruntime.FieldSSHPrivateKey, field.TypeString, value)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentruntime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentRuntimeUpdateOne is the builder for updating a single AgentRuntime entity.
type AgentRuntimeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AgentRuntimeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentRuntimeUpdateOne) SetUpdatedAt(v time.Time) *AgentRuntimeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentRuntimeUpdateOne) SetDeletedAt(v int) *AgentRuntimeUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableDeletedAt(v *int) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AgentRuntimeUpdateOne) AddDeletedAt(v int) *AgentRuntimeUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentRuntimeUpdateOne) SetName(v string) *AgentRuntimeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableName(v *string) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AgentRuntimeUpdateOne) SetType(v agentruntime.Type) *AgentRuntimeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableType(v *agentruntime.Type) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentRuntimeUpdateOne) SetStatus(v agentruntime.Status) *AgentRuntimeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableStatus(v *agentruntime.Status) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *AgentRuntimeUpdateOne) SetHost(v string) *AgentRuntimeUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableHost(v *string) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetUser sets the "user" field.
func (_u *AgentRuntimeUpdateOne) SetUser(v string) *AgentRuntimeUpdateOne {
	_u.mutation.SetUser(v)
	return _u
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableUser(v *string) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetUser(*v)
	}
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *AgentRuntimeUpdateOne) SetAuthMethod(v agentruntime.AuthMethod) *AgentRuntimeUpdateOne {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableAuthMethod(v *agentruntime.AuthMethod) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *AgentRuntimeUpdateOne) SetPassword(v string) *AgentRuntimeUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillablePassword(v *string) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSSHPrivateKey sets the "ssh_private_key" field.
func (_u *AgentRuntimeUpdateOne) SetSSHPrivateKey(v string) *AgentRuntimeUpdateOne {
	_u.mutation.SetSSHPrivateKey(v)
	return _u
}

// SetNillableSSHPrivateKey sets the "ssh_private_key" field if the given value is not nil.
func (_u *AgentRuntimeUpdateOne) SetNillableSSHPrivateKey(v *string) *AgentRuntimeUpdateOne {
	if v != nil {
		_u.SetSSHPrivateKey(*v)
	}
	return _u
}

// AddInstanceIDs adds the "instances" edge to the AgentInstance entity by IDs.
func (_u *AgentRuntimeUpdateOne) AddInstanceIDs(ids ...int) *AgentRuntimeUpdateOne {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the AgentInstance entity.
func (_u *AgentRuntimeUpdateOne) AddInstances(v ...*AgentInstance) *AgentRuntimeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// Mutation returns the AgentRuntimeMutation object of the builder.
func (_u *AgentRuntimeUpdateOne) Mutation() *AgentRuntimeMutation {
	return _u.mutation
}

// ClearInstances clears all "instances" edges to the AgentInstance entity.
func (_u *AgentRuntimeUpdateOne) ClearInstances() *AgentRuntimeUpdateOne {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to AgentInstance entities by IDs.
func (_u *AgentRuntimeUpdateOne) RemoveInstanceIDs(ids ...int) *AgentRuntimeUpdateOne {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to AgentInstance entities.
func (_u *AgentRuntimeUpdateOne) RemoveInstances(v ...*AgentInstance) *AgentRuntimeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// Where appends a list predicates to the AgentRuntimeUpdate builder.
func (_u *AgentRuntimeUpdateOne) Where(ps ...predicate.AgentRuntime) *AgentRuntimeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentRuntimeUpdateOne) Select(field string, fields ...string) *AgentRuntimeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentRuntime entity.
func (_u *AgentRuntimeUpdateOne) Save(ctx context.Context) (*AgentRuntime, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentRuntimeUpdateOne) SaveX(ctx context.Context) *AgentRuntime {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentRuntimeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentRuntimeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentRuntimeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentruntime.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentruntime.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentruntime.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentRuntimeUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := agentruntime.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentruntime.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := agentruntime.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.auth_method": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentRuntimeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentRuntimeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentRuntimeUpdateOne) sqlSave(ctx context.Context) (_node *AgentRuntime, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentruntime.Table, agentruntime.Columns, sqlgraph.NewFieldSpec(agentruntime.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentRuntime.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentruntime.FieldID)
		for _, f := range fields {
			if !agentruntime.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentruntime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentruntime.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentruntime.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(agentruntime.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentruntime.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(agentruntime.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentruntime.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(agentruntime.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.User(); ok {
		_spec.SetField(agentruntime.FieldUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(agentruntime.FieldAuthMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(agentruntime.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.SSHPrivateKey(); ok {
		_spec.SetField(agentruntime.FieldSSHPrivateKey, field.TypeString, value)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AgentRuntime{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentruntime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
