// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentmessage"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// AgentMessageUpdate is the builder for updating AgentMessage entities.
type AgentMessageUpdate struct {
	config
	hooks     []Hook
	mutation  *AgentMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AgentMessageUpdate builder.
func (_u *AgentMessageUpdate) Where(ps ...predicate.AgentMessage) *AgentMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentMessageUpdate) SetUpdatedAt(v time.Time) *AgentMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentMessageUpdate) SetDeletedAt(v int) *AgentMessageUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableDeletedAt(v *int) *AgentMessageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AgentMessageUpdate) AddDeletedAt(v int) *AgentMessageUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetDirection sets the "direction" field.
func (_u *AgentMessageUpdate) SetDirection(v agentmessage.Direction) *AgentMessageUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableDirection(v *agentmessage.Direction) *AgentMessageUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *AgentMessageUpdate) SetSenderType(v agentmessage.SenderType) *AgentMessageUpdate {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableSenderType(v *agentmessage.SenderType) *AgentMessageUpdate {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *AgentMessageUpdate) SetSenderID(v int) *AgentMessageUpdate {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableSenderID(v *int) *AgentMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *AgentMessageUpdate) AddSenderID(v int) *AgentMessageUpdate {
	_u.mutation.AddSenderID(v)
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *AgentMessageUpdate) ClearSenderID() *AgentMessageUpdate {
	_u.mutation.ClearSenderID()
	return _u
}

// SetType sets the "type" field.
func (_u *AgentMessageUpdate) SetType(v agentmessage.Type) *AgentMessageUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableType(v *agentmessage.Type) *AgentMessageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *AgentMessageUpdate) SetCorrelationID(v string) *AgentMessageUpdate {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableCorrelationID(v *string) *AgentMessageUpdate {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *AgentMessageUpdate) SetContent(v objects.JSONRawMessage) *AgentMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// AppendContent appends value to the "content" field.
func (_u *AgentMessageUpdate) AppendContent(v objects.JSONRawMessage) *AgentMessageUpdate {
	_u.mutation.AppendContent(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentMessageUpdate) SetStatus(v agentmessage.Status) *AgentMessageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableStatus(v *agentmessage.Status) *AgentMessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *AgentMessageUpdate) SetSequence(v int64) *AgentMessageUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableSequence(v *int64) *AgentMessageUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *AgentMessageUpdate) AddSequence(v int64) *AgentMessageUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AgentMessageUpdate) SetExpiresAt(v time.Time) *AgentMessageUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AgentMessageUpdate) SetNillableExpiresAt(v *time.Time) *AgentMessageUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AgentMessageUpdate) ClearExpiresAt() *AgentMessageUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the AgentMessageMutation object of the builder.
func (_u *AgentMessageUpdate) Mutation() *AgentMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentMessageUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentMessageUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentmessage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentmessage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentMessageUpdate) check() error {
	if v, ok := _u.mutation.Direction(); ok {
		if err := agentmessage.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderType(); ok {
		if err := agentmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := agentmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.status": %w`, err)}
		}
	}
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentMessage.agent"`)
	}
	if _u.mutation.AgentInstanceCleared() && len(_u.mutation.AgentInstanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentMessage.agent_instance"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentMessageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentMessageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentmessage.Table, agentmessage.Columns, sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentmessage.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(agentmessage.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(agentmessage.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(agentmessage.FieldSenderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(agentmessage.FieldSenderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(agentmessage.FieldSenderID, field.TypeInt, value)
	}
	if _u.mutation.SenderIDCleared() {
		_spec.ClearField(agentmessage.FieldSenderID, field.TypeInt)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(agentmessage.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(agentmessage.FieldCorrelationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(agentmessage.FieldContent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContent(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentmessage.FieldContent, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentmessage.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(agentmessage.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(agentmessage.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(agentmessage.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(agentmessage.FieldExpiresAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentMessageUpdateOne is the builder for updating a single AgentMessage entity.
type AgentMessageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AgentMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentMessageUpdateOne) SetUpdatedAt(v time.Time) *AgentMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentMessageUpdateOne) SetDeletedAt(v int) *AgentMessageUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableDeletedAt(v *int) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AgentMessageUpdateOne) AddDeletedAt(v int) *AgentMessageUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetDirection sets the "direction" field.
func (_u *AgentMessageUpdateOne) SetDirection(v agentmessage.Direction) *AgentMessageUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableDirection(v *agentmessage.Direction) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *AgentMessageUpdateOne) SetSenderType(v agentmessage.SenderType) *AgentMessageUpdateOne {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableSenderType(v *agentmessage.SenderType) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *AgentMessageUpdateOne) SetSenderID(v int) *AgentMessageUpdateOne {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableSenderID(v *int) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *AgentMessageUpdateOne) AddSenderID(v int) *AgentMessageUpdateOne {
	_u.mutation.AddSenderID(v)
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *AgentMessageUpdateOne) ClearSenderID() *AgentMessageUpdateOne {
	_u.mutation.ClearSenderID()
	return _u
}

// SetType sets the "type" field.
func (_u *AgentMessageUpdateOne) SetType(v agentmessage.Type) *AgentMessageUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableType(v *agentmessage.Type) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *AgentMessageUpdateOne) SetCorrelationID(v string) *AgentMessageUpdateOne {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableCorrelationID(v *string) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *AgentMessageUpdateOne) SetContent(v objects.JSONRawMessage) *AgentMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// AppendContent appends value to the "content" field.
func (_u *AgentMessageUpdateOne) AppendContent(v objects.JSONRawMessage) *AgentMessageUpdateOne {
	_u.mutation.AppendContent(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentMessageUpdateOne) SetStatus(v agentmessage.Status) *AgentMessageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableStatus(v *agentmessage.Status) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *AgentMessageUpdateOne) SetSequence(v int64) *AgentMessageUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableSequence(v *int64) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *AgentMessageUpdateOne) AddSequence(v int64) *AgentMessageUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AgentMessageUpdateOne) SetExpiresAt(v time.Time) *AgentMessageUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AgentMessageUpdateOne) SetNillableExpiresAt(v *time.Time) *AgentMessageUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AgentMessageUpdateOne) ClearExpiresAt() *AgentMessageUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the AgentMessageMutation object of the builder.
func (_u *AgentMessageUpdateOne) Mutation() *AgentMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentMessageUpdate builder.
func (_u *AgentMessageUpdateOne) Where(ps ...predicate.AgentMessage) *AgentMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentMessageUpdateOne) Select(field string, fields ...string) *AgentMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentMessage entity.
func (_u *AgentMessageUpdateOne) Save(ctx context.Context) (*AgentMessage, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentMessageUpdateOne) SaveX(ctx context.Context) *AgentMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentMessageUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentmessage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentmessage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Direction(); ok {
		if err := agentmessage.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderType(); ok {
		if err := agentmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := agentmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentMessage.status": %w`, err)}
		}
	}
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentMessage.agent"`)
	}
	if _u.mutation.AgentInstanceCleared() && len(_u.mutation.AgentInstanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentMessage.agent_instance"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentMessageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentMessageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentMessageUpdateOne) sqlSave(ctx context.Context) (_node *AgentMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentmessage.Table, agentmessage.Columns, sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentmessage.FieldID)
		for _, f := range fields {
			if !agentmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentmessage.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(agentmessage.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(agentmessage.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(agentmessage.FieldSenderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(agentmessage.FieldSenderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(agentmessage.FieldSenderID, field.TypeInt, value)
	}
	if _u.mutation.SenderIDCleared() {
		_spec.ClearField(agentmessage.FieldSenderID, field.TypeInt)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(agentmessage.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(agentmessage.FieldCorrelationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(agentmessage.FieldContent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContent(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentmessage.FieldContent, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentmessage.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(agentmessage.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(agentmessage.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(agentmessage.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(agentmessage.FieldExpiresAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AgentMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
