// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentinstance"
	"github.com/looplj/axonhub/internal/ent/agentruntime"
)

// AgentRuntimeCreate is the builder for creating a AgentRuntime entity.
type AgentRuntimeCreate struct {
	config
	mutation *AgentRuntimeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentRuntimeCreate) SetCreatedAt(v time.Time) *AgentRuntimeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableCreatedAt(v *time.Time) *AgentRuntimeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentRuntimeCreate) SetUpdatedAt(v time.Time) *AgentRuntimeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableUpdatedAt(v *time.Time) *AgentRuntimeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AgentRuntimeCreate) SetDeletedAt(v int) *AgentRuntimeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableDeletedAt(v *int) *AgentRuntimeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AgentRuntimeCreate) SetName(v string) *AgentRuntimeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *AgentRuntimeCreate) SetType(v agentruntime.Type) *AgentRuntimeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableType(v *agentruntime.Type) *AgentRuntimeCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentRuntimeCreate) SetStatus(v agentruntime.Status) *AgentRuntimeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableStatus(v *agentruntime.Status) *AgentRuntimeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHost sets the "host" field.
func (_c *AgentRuntimeCreate) SetHost(v string) *AgentRuntimeCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableHost(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetUser sets the "user" field.
func (_c *AgentRuntimeCreate) SetUser(v string) *AgentRuntimeCreate {
	_c.mutation.SetUser(v)
	return _c
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableUser(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetUser(*v)
	}
	return _c
}

// SetAuthMethod sets the "auth_method" field.
func (_c *AgentRuntimeCreate) SetAuthMethod(v agentruntime.AuthMethod) *AgentRuntimeCreate {
	_c.mutation.SetAuthMethod(v)
	return _c
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableAuthMethod(v *agentruntime.AuthMethod) *AgentRuntimeCreate {
	if v != nil {
		_c.SetAuthMethod(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *AgentRuntimeCreate) SetPassword(v string) *AgentRuntimeCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillablePassword(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetSSHPrivateKey sets the "ssh_private_key" field.
func (_c *AgentRuntimeCreate) SetSSHPrivateKey(v string) *AgentRuntimeCreate {
	_c.mutation.SetSSHPrivateKey(v)
	return _c
}

// SetNillableSSHPrivateKey sets the "ssh_private_key" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableSSHPrivateKey(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetSSHPrivateKey(*v)
	}
	return _c
}

// AddInstanceIDs adds the "instances" edge to the AgentInstance entity by IDs.
func (_c *AgentRuntimeCreate) AddInstanceIDs(ids ...int) *AgentRuntimeCreate {
	_c.mutation.AddInstanceIDs(ids...)
	return _c
}

// AddInstances adds the "instances" edges to the AgentInstance entity.
func (_c *AgentRuntimeCreate) AddInstances(v ...*AgentInstance) *AgentRuntimeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInstanceIDs(ids...)
}

// Mutation returns the AgentRuntimeMutation object of the builder.
func (_c *AgentRuntimeCreate) Mutation() *AgentRuntimeMutation {
	return _c.mutation
}

// Save creates the AgentRuntime in the database.
func (_c *AgentRuntimeCreate) Save(ctx context.Context) (*AgentRuntime, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentRuntimeCreate) SaveX(ctx context.Context) *AgentRuntime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentRuntimeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentRuntimeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentRuntimeCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if agentruntime.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentruntime.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := agentruntime.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if agentruntime.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentruntime.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentruntime.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := agentruntime.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := agentruntime.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := agentruntime.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Host(); !ok {
		v := agentruntime.DefaultHost
		_c.mutation.SetHost(v)
	}
	if _, ok := _c.mutation.User(); !ok {
		v := agentruntime.DefaultUser
		_c.mutation.SetUser(v)
	}
	if _, ok := _c.mutation.AuthMethod(); !ok {
		v := agentruntime.DefaultAuthMethod
		_c.mutation.SetAuthMethod(v)
	}
	if _, ok := _c.mutation.Password(); !ok {
		v := agentruntime.DefaultPassword
		_c.mutation.SetPassword(v)
	}
	if _, ok := _c.mutation.SSHPrivateKey(); !ok {
		v := agentruntime.DefaultSSHPrivateKey
		_c.mutation.SetSSHPrivateKey(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentRuntimeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentRuntime.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentRuntime.updated_at"`)}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "AgentRuntime.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentRuntime.name"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AgentRuntime.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := agentruntime.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentRuntime.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := agentruntime.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "AgentRuntime.host"`)}
	}
	if _, ok := _c.mutation.User(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required field "AgentRuntime.user"`)}
	}
	if _, ok := _c.mutation.AuthMethod(); !ok {
		return &ValidationError{Name: "auth_method", err: errors.New(`ent: missing required field "AgentRuntime.auth_method"`)}
	}
	if v, ok := _c.mutation.AuthMethod(); ok {
		if err := agentruntime.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.auth_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "AgentRuntime.password"`)}
	}
	if _, ok := _c.mutation.SSHPrivateKey(); !ok {
		return &ValidationError{Name: "ssh_private_key", err: errors.New(`ent: missing required field "AgentRuntime.ssh_private_key"`)}
	}
	return nil
}

func (_c *AgentRuntimeCreate) sqlSave(ctx context.Context) (*AgentRuntime, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentRuntimeCreate) createSpec() (*AgentRuntime, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentRuntime{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentruntime.Table, sqlgraph.NewFieldSpec(agentruntime.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentruntime.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentruntime.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(agentruntime.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentruntime.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(agentruntime.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentruntime.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(agentruntime.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.User(); ok {
		_spec.SetField(agentruntime.FieldUser, field.TypeString, value)
		_node.User = value
	}
	if value, ok := _c.mutation.AuthMethod(); ok {
		_spec.SetField(agentruntime.FieldAuthMethod, field.TypeEnum, value)
		_node.AuthMethod = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(agentruntime.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.SSHPrivateKey(); ok {
		_spec.SetField(agentruntime.FieldSSHPrivateKey, field.TypeString, value)
		_node.SSHPrivateKey = value
	}
	if nodes := _c.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentruntime.InstancesTable,
			Columns: []string{agentruntime.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentRuntime.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentRuntimeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentRuntimeCreate) OnConflict(opts ...sql.ConflictOption) *AgentRuntimeUpsertOne {
	_c.conflict = opts
	return &AgentRuntimeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentRuntime.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentRuntimeCreate) OnConflictColumns(columns ...string) *AgentRuntimeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentRuntimeUpsertOne{
		create: _c,
	}
}

type (
	// AgentRuntimeUpsertOne is the builder for "upsert"-ing
	//  one AgentRuntime node.
	AgentRuntimeUpsertOne struct {
		create *AgentRuntimeCreate
	}

	// AgentRuntimeUpsert is the "OnConflict" setter.
	AgentRuntimeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentRuntimeUpsert) SetUpdatedAt(v time.Time) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateUpdatedAt() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AgentRuntimeUpsert) SetDeletedAt(v int) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateDeletedAt() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AgentRuntimeUpsert) AddDeletedAt(v int) *AgentRuntimeUpsert {
	u.Add(agentruntime.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *AgentRuntimeUpsert) SetName(v string) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateName() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *AgentRuntimeUpsert) SetType(v agentruntime.Type) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateType() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldType)
	return u
}

// SetStatus sets the "status" field.
func (u *AgentRuntimeUpsert) SetStatus(v agentruntime.Status) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateStatus() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldStatus)
	return u
}

// SetHost sets the "host" field.
func (u *AgentRuntimeUpsert) SetHost(v string) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldHost, v)
	return u
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateHost() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldHost)
	return u
}

// SetUser sets the "user" field.
func (u *AgentRuntimeUpsert) SetUser(v string) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldUser, v)
	return u
}

// UpdateUser sets the "user" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateUser() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldUser)
	return u
}

// SetAuthMethod sets the "auth_method" field.
func (u *AgentRuntimeUpsert) SetAuthMethod(v agentruntime.AuthMethod) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldAuthMethod, v)
	return u
}

// UpdateAuthMethod sets the "auth_method" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateAuthMethod() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldAuthMethod)
	return u
}

// SetPassword sets the "password" field.
func (u *AgentRuntimeUpsert) SetPassword(v string) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdatePassword() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldPassword)
	return u
}

// SetSSHPrivateKey sets the "ssh_private_key" field.
func (u *AgentRuntimeUpsert) SetSSHPrivateKey(v string) *AgentRuntimeUpsert {
	u.Set(agentruntime.FieldSSHPrivateKey, v)
	return u
}

// UpdateSSHPrivateKey sets the "ssh_private_key" field to the value that was provided on create.
func (u *AgentRuntimeUpsert) UpdateSSHPrivateKey() *AgentRuntimeUpsert {
	u.SetExcluded(agentruntime.FieldSSHPrivateKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AgentRuntime.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentRuntimeUpsertOne) UpdateNewValues() *AgentRuntimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agentruntime.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentRuntime.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentRuntimeUpsertOne) Ignore() *AgentRuntimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentRuntimeUpsertOne) DoNothing() *AgentRuntimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentRuntimeCreate.OnConflict
// documentation for more info.
func (u *AgentRuntimeUpsertOne) Update(set func(*AgentRuntimeUpsert)) *AgentRuntimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentRuntimeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentRuntimeUpsertOne) SetUpdatedAt(v time.Time) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateUpdatedAt() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AgentRuntimeUpsertOne) SetDeletedAt(v int) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AgentRuntimeUpsertOne) AddDeletedAt(v int) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateDeletedAt() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *AgentRuntimeUpsertOne) SetName(v string) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateName() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *AgentRuntimeUpsertOne) SetType(v agentruntime.Type) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateType() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *AgentRuntimeUpsertOne) SetStatus(v agentruntime.Status) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateStatus() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateStatus()
	})
}

// SetHost sets the "host" field.
func (u *AgentRuntimeUpsertOne) SetHost(v string) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetHost(v)
	})
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateHost() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateHost()
	})
}

// SetUser sets the "user" field.
func (u *AgentRuntimeUpsertOne) SetUser(v string) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetUser(v)
	})
}

// UpdateUser sets the "user" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateUser() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateUser()
	})
}

// SetAuthMethod sets the "auth_method" field.
func (u *AgentRuntimeUpsertOne) SetAuthMethod(v agentruntime.AuthMethod) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetAuthMethod(v)
	})
}

// UpdateAuthMethod sets the "auth_method" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateAuthMethod() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateAuthMethod()
	})
}

// SetPassword sets the "password" field.
func (u *AgentRuntimeUpsertOne) SetPassword(v string) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdatePassword() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdatePassword()
	})
}

// SetSSHPrivateKey sets the "ssh_private_key" field.
func (u *AgentRuntimeUpsertOne) SetSSHPrivateKey(v string) *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetSSHPrivateKey(v)
	})
}

// UpdateSSHPrivateKey sets the "ssh_private_key" field to the value that was provided on create.
func (u *AgentRuntimeUpsertOne) UpdateSSHPrivateKey() *AgentRuntimeUpsertOne {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateSSHPrivateKey()
	})
}

// Exec executes the query.
func (u *AgentRuntimeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentRuntimeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentRuntimeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentRuntimeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentRuntimeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentRuntimeCreateBulk is the builder for creating many AgentRuntime entities in bulk.
type AgentRuntimeCreateBulk struct {
	config
	err      error
	builders []*AgentRuntimeCreate
	conflict []sql.ConflictOption
}

// Save creates the AgentRuntime entities in the database.
func (_c *AgentRuntimeCreateBulk) Save(ctx context.Context) ([]*AgentRuntime, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentRuntime, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentRuntimeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentRuntimeCreateBulk) SaveX(ctx context.Context) []*AgentRuntime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentRuntimeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentRuntimeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentRuntime.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentRuntimeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentRuntimeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentRuntimeUpsertBulk {
	_c.conflict = opts
	return &AgentRuntimeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentRuntime.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentRuntimeCreateBulk) OnConflictColumns(columns ...string) *AgentRuntimeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentRuntimeUpsertBulk{
		create: _c,
	}
}

// AgentRuntimeUpsertBulk is the builder for "upsert"-ing
// a bulk of AgentRuntime nodes.
type AgentRuntimeUpsertBulk struct {
	create *AgentRuntimeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AgentRuntime.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentRuntimeUpsertBulk) UpdateNewValues() *AgentRuntimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agentruntime.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentRuntime.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentRuntimeUpsertBulk) Ignore() *AgentRuntimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentRuntimeUpsertBulk) DoNothing() *AgentRuntimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentRuntimeCreateBulk.OnConflict
// documentation for more info.
func (u *AgentRuntimeUpsertBulk) Update(set func(*AgentRuntimeUpsert)) *AgentRuntimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentRuntimeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentRuntimeUpsertBulk) SetUpdatedAt(v time.Time) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateUpdatedAt() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AgentRuntimeUpsertBulk) SetDeletedAt(v int) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AgentRuntimeUpsertBulk) AddDeletedAt(v int) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateDeletedAt() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *AgentRuntimeUpsertBulk) SetName(v string) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateName() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *AgentRuntimeUpsertBulk) SetType(v agentruntime.Type) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateType() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *AgentRuntimeUpsertBulk) SetStatus(v agentruntime.Status) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateStatus() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateStatus()
	})
}

// SetHost sets the "host" field.
func (u *AgentRuntimeUpsertBulk) SetHost(v string) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetHost(v)
	})
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateHost() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateHost()
	})
}

// SetUser sets the "user" field.
func (u *AgentRuntimeUpsertBulk) SetUser(v string) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetUser(v)
	})
}

// UpdateUser sets the "user" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateUser() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateUser()
	})
}

// SetAuthMethod sets the "auth_method" field.
func (u *AgentRuntimeUpsertBulk) SetAuthMethod(v agentruntime.AuthMethod) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetAuthMethod(v)
	})
}

// UpdateAuthMethod sets the "auth_method" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateAuthMethod() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateAuthMethod()
	})
}

// SetPassword sets the "password" field.
func (u *AgentRuntimeUpsertBulk) SetPassword(v string) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdatePassword() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdatePassword()
	})
}

// SetSSHPrivateKey sets the "ssh_private_key" field.
func (u *AgentRuntimeUpsertBulk) SetSSHPrivateKey(v string) *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.SetSSHPrivateKey(v)
	})
}

// UpdateSSHPrivateKey sets the "ssh_private_key" field to the value that was provided on create.
func (u *AgentRuntimeUpsertBulk) UpdateSSHPrivateKey() *AgentRuntimeUpsertBulk {
	return u.Update(func(s *AgentRuntimeUpsert) {
		s.UpdateSSHPrivateKey()
	})
}

// Exec executes the query.
func (u *AgentRuntimeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentRuntimeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentRuntimeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentRuntimeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
