// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentinstance"
	"github.com/looplj/axonhub/internal/ent/agentruntime"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// AgentRuntimeQuery is the builder for querying AgentRuntime entities.
type AgentRuntimeQuery struct {
	config
	ctx                *QueryContext
	order              []agentruntime.OrderOption
	inters             []Interceptor
	predicates         []predicate.AgentRuntime
	withInstances      *AgentInstanceQuery
	loadTotal          []func(context.Context, []*AgentRuntime) error
	modifiers          []func(*sql.Selector)
	withNamedInstances map[string]*AgentInstanceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentRuntimeQuery builder.
func (_q *AgentRuntimeQuery) Where(ps ...predicate.AgentRuntime) *AgentRuntimeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AgentRuntimeQuery) Limit(limit int) *AgentRuntimeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AgentRuntimeQuery) Offset(offset int) *AgentRuntimeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AgentRuntimeQuery) Unique(unique bool) *AgentRuntimeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AgentRuntimeQuery) Order(o ...agentruntime.OrderOption) *AgentRuntimeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryInstances chains the current query on the "instances" edge.
func (_q *AgentRuntimeQuery) QueryInstances() *AgentInstanceQuery {
	query := (&AgentInstanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agentruntime.Table, agentruntime.FieldID, selector),
			sqlgraph.To(agentinstance.Table, agentinstance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agentruntime.InstancesTable, agentruntime.InstancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AgentRuntime entity from the query.
// Returns a *NotFoundError when no AgentRuntime was found.
func (_q *AgentRuntimeQuery) First(ctx context.Context) (*AgentRuntime, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agentruntime.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AgentRuntimeQuery) FirstX(ctx context.Context) *AgentRuntime {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentRuntime ID from the query.
// Returns a *NotFoundError when no AgentRuntime ID was found.
func (_q *AgentRuntimeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agentruntime.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AgentRuntimeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentRuntime entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentRuntime entity is found.
// Returns a *NotFoundError when no AgentRuntime entities are found.
func (_q *AgentRuntimeQuery) Only(ctx context.Context) (*AgentRuntime, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agentruntime.Label}
	default:
		return nil, &NotSingularError{agentruntime.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AgentRuntimeQuery) OnlyX(ctx context.Context) *AgentRuntime {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentRuntime ID in the query.
// Returns a *NotSingularError when more than one AgentRuntime ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AgentRuntimeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agentruntime.Label}
	default:
		err = &NotSingularError{agentruntime.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AgentRuntimeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentRuntimes.
func (_q *AgentRuntimeQuery) All(ctx context.Context) ([]*AgentRuntime, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentRuntime, *AgentRuntimeQuery]()
	return withInterceptors[[]*AgentRuntime](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AgentRuntimeQuery) AllX(ctx context.Context) []*AgentRuntime {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentRuntime IDs.
func (_q *AgentRuntimeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(agentruntime.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AgentRuntimeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AgentRuntimeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AgentRuntimeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AgentRuntimeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AgentRuntimeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AgentRuntimeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentRuntimeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AgentRuntimeQuery) Clone() *AgentRuntimeQuery {
	if _q == nil {
		return nil
	}
	return &AgentRuntimeQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]agentruntime.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.AgentRuntime{}, _q.predicates...),
		withInstances: _q.withInstances.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithInstances tells the query-builder to eager-load the nodes that are connected to
// the "instances" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AgentRuntimeQuery) WithInstances(opts ...func(*AgentInstanceQuery)) *AgentRuntimeQuery {
	query := (&AgentInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInstances = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentRuntime.Query().
//		GroupBy(agentruntime.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AgentRuntimeQuery) GroupBy(field string, fields ...string) *AgentRuntimeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentRuntimeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = agentruntime.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AgentRuntime.Query().
//		Select(agentruntime.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AgentRuntimeQuery) Select(fields ...string) *AgentRuntimeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AgentRuntimeSelect{AgentRuntimeQuery: _q}
	sbuild.label = agentruntime.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentRuntimeSelect configured with the given aggregations.
func (_q *AgentRuntimeQuery) Aggregate(fns ...AggregateFunc) *AgentRuntimeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AgentRuntimeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !agentruntime.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if agentruntime.Policy == nil {
		return errors.New("ent: uninitialized agentruntime.Policy (forgotten import ent/runtime?)")
	}
	if err := agentruntime.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *AgentRuntimeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentRuntime, error) {
	var (
		nodes       = []*AgentRuntime{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withInstances != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentRuntime).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentRuntime{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withInstances; query != nil {
		if err := _q.loadInstances(ctx, query, nodes,
			func(n *AgentRuntime) { n.Edges.Instances = []*AgentInstance{} },
			func(n *AgentRuntime, e *AgentInstance) { n.Edges.Instances = append(n.Edges.Instances, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedInstances {
		if err := _q.loadInstances(ctx, query, nodes,
			func(n *AgentRuntime) { n.appendNamedInstances(name) },
			func(n *AgentRuntime, e *AgentInstance) { n.appendNamedInstances(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AgentRuntimeQuery) loadInstances(ctx context.Context, query *AgentInstanceQuery, nodes []*AgentRuntime, init func(*AgentRuntime), assign func(*AgentRuntime, *AgentInstance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AgentRuntime)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentinstance.FieldAgentRuntimeID)
	}
	query.Where(predicate.AgentInstance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agentruntime.InstancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentRuntimeID
		if fk == nil {
			return fmt.Errorf(`foreign-key "agent_runtime_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_runtime_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AgentRuntimeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AgentRuntimeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agentruntime.Table, agentruntime.Columns, sqlgraph.NewFieldSpec(agentruntime.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentruntime.FieldID)
		for i := range fields {
			if fields[i] != agentruntime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AgentRuntimeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(agentruntime.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = agentruntime.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AgentRuntimeQuery) Modify(modifiers ...func(s *sql.Selector)) *AgentRuntimeSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedInstances tells the query-builder to eager-load the nodes that are connected to the "instances"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *AgentRuntimeQuery) WithNamedInstances(name string, opts ...func(*AgentInstanceQuery)) *AgentRuntimeQuery {
	query := (&AgentInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedInstances == nil {
		_q.withNamedInstances = make(map[string]*AgentInstanceQuery)
	}
	_q.withNamedInstances[name] = query
	return _q
}

// AgentRuntimeGroupBy is the group-by builder for AgentRuntime entities.
type AgentRuntimeGroupBy struct {
	selector
	build *AgentRuntimeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AgentRuntimeGroupBy) Aggregate(fns ...AggregateFunc) *AgentRuntimeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AgentRuntimeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentRuntimeQuery, *AgentRuntimeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AgentRuntimeGroupBy) sqlScan(ctx context.Context, root *AgentRuntimeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentRuntimeSelect is the builder for selecting fields of AgentRuntime entities.
type AgentRuntimeSelect struct {
	*AgentRuntimeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AgentRuntimeSelect) Aggregate(fns ...AggregateFunc) *AgentRuntimeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AgentRuntimeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentRuntimeQuery, *AgentRuntimeSelect](ctx, _s.AgentRuntimeQuery, _s, _s.inters, v)
}

func (_s *AgentRuntimeSelect) sqlScan(ctx context.Context, root *AgentRuntimeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AgentRuntimeSelect) Modify(modifiers ...func(s *sql.Selector)) *AgentRuntimeSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
