// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/agentruntime"
)

// AgentRuntime is the model entity for the AgentRuntime schema.
type AgentRuntime struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Runtime name
	Name string `json:"name,omitempty"`
	// Runtime type: vm, docker or local
	Type agentruntime.Type `json:"type,omitempty"`
	// Runtime status
	Status agentruntime.Status `json:"status,omitempty"`
	// Runtime host address
	Host string `json:"host,omitempty"`
	// Runtime user for authentication
	User string `json:"user,omitempty"`
	// Authentication method: password or ssh_key
	AuthMethod agentruntime.AuthMethod `json:"auth_method,omitempty"`
	// Runtime password for authentication
	Password string `json:"-"`
	// SSH private key for authentication
	SSHPrivateKey string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentRuntimeQuery when eager-loading is set.
	Edges        AgentRuntimeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentRuntimeEdges holds the relations/edges for other nodes in the graph.
type AgentRuntimeEdges struct {
	// Instances holds the value of the instances edge.
	Instances []*AgentInstance `json:"instances,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedInstances map[string][]*AgentInstance
}

// InstancesOrErr returns the Instances value or an error if the edge
// was not loaded in eager-loading.
func (e AgentRuntimeEdges) InstancesOrErr() ([]*AgentInstance, error) {
	if e.loadedTypes[0] {
		return e.Instances, nil
	}
	return nil, &NotLoadedError{edge: "instances"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentRuntime) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentruntime.FieldID, agentruntime.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case agentruntime.FieldName, agentruntime.FieldType, agentruntime.FieldStatus, agentruntime.FieldHost, agentruntime.FieldUser, agentruntime.FieldAuthMethod, agentruntime.FieldPassword, agentruntime.FieldSSHPrivateKey:
			values[i] = new(sql.NullString)
		case agentruntime.FieldCreatedAt, agentruntime.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentRuntime fields.
func (_m *AgentRuntime) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentruntime.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agentruntime.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentruntime.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agentruntime.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case agentruntime.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agentruntime.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = agentruntime.Type(value.String)
			}
		case agentruntime.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agentruntime.Status(value.String)
			}
		case agentruntime.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case agentruntime.FieldUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user", values[i])
			} else if value.Valid {
				_m.User = value.String
			}
		case agentruntime.FieldAuthMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_method", values[i])
			} else if value.Valid {
				_m.AuthMethod = agentruntime.AuthMethod(value.String)
			}
		case agentruntime.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case agentruntime.FieldSSHPrivateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_private_key", values[i])
			} else if value.Valid {
				_m.SSHPrivateKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentRuntime.
// This includes values selected through modifiers, order, etc.
func (_m *AgentRuntime) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstances queries the "instances" edge of the AgentRuntime entity.
func (_m *AgentRuntime) QueryInstances() *AgentInstanceQuery {
	return NewAgentRuntimeClient(_m.config).QueryInstances(_m)
}

// Update returns a builder for updating this AgentRuntime.
// Note that you need to call AgentRuntime.Unwrap() before calling this method if this AgentRuntime
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentRuntime) Update() *AgentRuntimeUpdateOne {
	return NewAgentRuntimeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentRuntime entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentRuntime) Unwrap() *AgentRuntime {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentRuntime is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentRuntime) String() string {
	var builder strings.Builder
	builder.WriteString("AgentRuntime(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("user=")
	builder.WriteString(_m.User)
	builder.WriteString(", ")
	builder.WriteString("auth_method=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMethod))
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("ssh_private_key=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// NamedInstances returns the Instances named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *AgentRuntime) NamedInstances(name string) ([]*AgentInstance, error) {
	if _m.Edges.namedInstances == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedInstances[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *AgentRuntime) appendNamedInstances(name string, edges ...*AgentInstance) {
	if _m.Edges.namedInstances == nil {
		_m.Edges.namedInstances = make(map[string][]*AgentInstance)
	}
	if len(edges) == 0 {
		_m.Edges.namedInstances[name] = []*AgentInstance{}
	} else {
		_m.Edges.namedInstances[name] = append(_m.Edges.namedInstances[name], edges...)
	}
}

// AgentRuntimes is a parsable slice of AgentRuntime.
type AgentRuntimes []*AgentRuntime
