package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/agentruntime"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/looplj/axonhub/internal/server/biz"
)

// Password is the resolver for the password field.
func (r *agentRuntimeResolver) Password(ctx context.Context, obj *ent.AgentRuntime) (*string, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteAgents) {
		return nil, nil
	}

	password := obj.Password

	return &password, nil
}

// SSHPrivateKey is the resolver for the sshPrivateKey field.
func (r *agentRuntimeResolver) SSHPrivateKey(ctx context.Context, obj *ent.AgentRuntime) (*string, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteAgents) {
		return nil, nil
	}

	sshPrivateKey := obj.SSHPrivateKey

	return &sshPrivateKey, nil
}

// CreateAgentRuntime is the resolver for the createAgentRuntime field.
func (r *mutationResolver) CreateAgentRuntime(ctx context.Context, input ent.CreateAgentRuntimeInput) (*ent.AgentRuntime, error) {
	return r.agentRuntimeService.CreateAgentRuntime(ctx, input)
}

// UpdateAgentRuntime is the resolver for the updateAgentRuntime field.
func (r *mutationResolver) UpdateAgentRuntime(ctx context.Context, id objects.GUID, input ent.UpdateAgentRuntimeInput) (*ent.AgentRuntime, error) {
	return r.agentRuntimeService.UpdateAgentRuntime(ctx, id.ID, input)
}

// UpdateAgentRuntimeStatus is the resolver for the updateAgentRuntimeStatus field.
func (r *mutationResolver) UpdateAgentRuntimeStatus(ctx context.Context, id objects.GUID, status agentruntime.Status) (*ent.AgentRuntime, error) {
	return r.agentRuntimeService.UpdateAgentRuntime(ctx, id.ID, ent.UpdateAgentRuntimeInput{
		Status: &status,
	})
}

// DeleteAgentRuntime is the resolver for the deleteAgentRuntime field.
func (r *mutationResolver) DeleteAgentRuntime(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.agentRuntimeService.DeleteAgentRuntime(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteAgentRuntimes is the resolver for the bulkDeleteAgentRuntimes field.
func (r *mutationResolver) BulkDeleteAgentRuntimes(ctx context.Context, ids []*objects.GUID) (bool, error) {
	intIDs := objects.IntGuids(ids)
	for _, id := range intIDs {
		if err := r.agentRuntimeService.DeleteAgentRuntime(ctx, id); err != nil {
			return false, err
		}
	}

	return true, nil
}

// BulkUpdateAgentRuntimeStatus is the resolver for the bulkUpdateAgentRuntimeStatus field.
func (r *mutationResolver) BulkUpdateAgentRuntimeStatus(ctx context.Context, ids []*objects.GUID, status agentruntime.Status) (bool, error) {
	intIDs := objects.IntGuids(ids)
	for _, id := range intIDs {
		_, err := r.agentRuntimeService.UpdateAgentRuntime(ctx, id, ent.UpdateAgentRuntimeInput{
			Status: &status,
		})
		if err != nil {
			return false, err
		}
	}

	return true, nil
}

// TestAgentRuntimeConnection is the resolver for the testAgentRuntimeConnection field.
func (r *mutationResolver) TestAgentRuntimeConnection(ctx context.Context, id objects.GUID) (*biz.TestConnectionResult, error) {
	return r.agentRuntimeService.TestConnection(ctx, id.ID)
}

// DeployAxonclaw is the resolver for the deployAxonclaw field.
func (r *mutationResolver) DeployAxonclaw(ctx context.Context, input biz.DeployAxonclawInput) (*biz.DeployAxonclawResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if input.AxonhubBaseURL == "" {
		return nil, fmt.Errorf("axonhub base url is required")
	}

	return r.agentDeployService.DeployAxonclaw(ctx, input)
}

// StopAxonclawInstance is the resolver for the stopAxonclawInstance field.
func (r *mutationResolver) StopAxonclawInstance(ctx context.Context, instanceID objects.GUID) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.StopAxonclawInstance(ctx, instanceID.ID)
}

// StartAxonclawInstance is the resolver for the startAxonclawInstance field.
func (r *mutationResolver) StartAxonclawInstance(ctx context.Context, instanceID objects.GUID) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.StartAxonclawInstance(ctx, instanceID.ID)
}

// RestartAxonclawInstance is the resolver for the restartAxonclawInstance field.
func (r *mutationResolver) RestartAxonclawInstance(ctx context.Context, instanceID objects.GUID) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.RestartAxonclawInstance(ctx, instanceID.ID)
}

// RedeployAxonclawInstance is the resolver for the redeployAxonclawInstance field.
func (r *mutationResolver) RedeployAxonclawInstance(ctx context.Context, instanceID objects.GUID, axonhubBaseURL *string) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.RedeployAxonclawInstance(ctx, instanceID.ID, axonhubBaseURL)
}

// AgentRuntime is the resolver for the agentRuntime field.
func (r *queryResolver) AgentRuntime(ctx context.Context, id objects.GUID) (*ent.AgentRuntime, error) {
	if id.Type != ent.TypeAgentRuntime {
		return nil, fmt.Errorf("invalid agent runtime id type")
	}
	return r.client.AgentRuntime.Query().
		Where(agentruntime.IDEQ(id.ID)).
		Only(ctx)
}
